name: Build Module

on:
  push:

jobs:
  build-inviwo-with-module:
    uses: xeTaiz/inviwo-marketplace/.github/workflows/inviwo.yml@updated
    with:
      ext_modules_repo: xeTaiz/inviwo-module-markettest
