name: Build Module

on:
  push:

env:
  MODULE_NAME: markettest

jobs:
  build-inviwo-with-module:
    uses: xeTaiz/inviwo-marketplace/.github/workflows/inviwo.yml@updated
    with:
      ext_modules_repo: ${{ github.repository }}
    
  release-module:
    needs: build-inviwo-with-module
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-20.04]
        include:
          - os: 'windows-latest'
            installer: 'inviwo-installer-win'
            builddir: 'build-dir-win'
            libprefix: '/build/bin/Release/inviwo-module-'
            libext: '.dll'
          - os: 'macos-latest'
            installer: 'inviwo-installer-macos'
            builddir: 'build-dir-macos'
            libprefix: 'build/lib/libinviwo-module-'
            libext: '.so'
          - os: 'ubuntu-20.04'
            installer: 'inviwo-installer-ubuntu'
            builddir: 'build-dir-ubuntu'
            libprefix: 'build/lib/libinviwo-module-'
            libext: '.so'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download Build dir artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        name: ${{ matrix.builddir }}

    - name: Zip Module Data
      uses: papeloto/action-zip@v1
      with:
        files: ${{ matrix.libprefix }}${{ env.MODULE_NAME }}${{ matrix.libext }} build/modules/${{ env.MODULE_NAME }}
        dest: ${{ env.MODULE_NAME }}.zip

    - name: Release Module Artifact
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: release/${{ github.sha }}-${{ runner.os }}
          release_name: Release ${{ github.sha }}-${{ runner.os }}
          body: |
            Automatic Release to Inviwo Marketplace.
          draft: false
          prerelease: false

    - name: Upload Release Assets
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./${{ env.MODULE_NAME }}.zip
        asset_name: ${{ env.MODULE_NAME }}.zip
        asset_content_type: application/zip
